name: deploy-manifests

on: 
  push:
    branches: 
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with: 
          token: ${{secrets.DIGOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment auth-depl
      - run: kubectrl apply -f infra/k8s
